/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Service.SachService;
import Service.SachService;
import Service.SachService;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sach;

/**
 *
 * @author FSC
 */
public class SachFrame extends javax.swing.JFrame {
    DefaultTableModel defaultTableModel;
    
    /**
     * Creates new form SachFrame
     */
    public SachFrame() throws SQLException {
        initComponents();
        DefaultTableModel defaultTableModel;
        SachService us = new SachService();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }

        };
        sachTableList.setModel(defaultTableModel);
        defaultTableModel.addColumn("idTaiLieu");
        defaultTableModel.addColumn("TenNXB");
        defaultTableModel.addColumn("SoBanPhatHanh");
        defaultTableModel.addColumn("TenTacGia");
        defaultTableModel.addColumn("SoTrang");
        setData(us.getAllSach());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sachTableList = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 200));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("SÁCH");

        sachTableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sachTableList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(sachTableList);

        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deleteBtn.setText("XÓA");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        refreshBtn.setText("REFRESH");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1)
                        .addGap(118, 118, 118)
                        .addComponent(deleteBtn)
                        .addGap(50, 50, 50)
                        .addComponent(refreshBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(jLabel1)
                    .addComponent(deleteBtn)
                    .addComponent(refreshBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new mainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        SachService us = new SachService();
        int row = sachTableList.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(SachFrame.this, "Vui lòng chọn Sách muốn xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int comfirm = JOptionPane.showConfirmDialog(SachFrame.this, "Bạn có chắc chắn muốn xóa!");

            if (comfirm == JOptionPane.YES_OPTION) {
                int ID = Integer.valueOf(String.valueOf(sachTableList.getValueAt(row, 0)));

                try {
                    us.deleteSach(ID);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(SachFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                try {
                    setData(us.getAllSach());
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(SachFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        SachService us = new SachService();
        try {
            setData(us.getAllSach());
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(SachFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed
    
    private void setData(List<Sach> sachs) throws SQLException {
        DefaultTableModel defaultTableModel;
        SachService us = new SachService();
        defaultTableModel = new DefaultTableModel();
        sachTableList.setModel(defaultTableModel);
        defaultTableModel.addColumn("id Tài Liệu");
        defaultTableModel.addColumn("Tên NXB");
        defaultTableModel.addColumn("Số Bản Phát Hành");
        defaultTableModel.addColumn("Tên tác giả");
        defaultTableModel.addColumn("Số Trang");
        for (Sach sach : sachs) {
            defaultTableModel.addRow(new Object[]{sach.getIdTaiLieu(), sach.getTenNXB(), sach.getSoBanPhatHanh(),
                sach.getTenTacGia(), sach.getSoTrang()});
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable sachTableList;
    // End of variables declaration//GEN-END:variables
}
