/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Service.TapChiService;
import com.sun.istack.internal.logging.Logger;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TapChi;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author FSC
 */
public class TapChiFrame extends javax.swing.JFrame {

    DefaultTableModel defaultTableModel;

    /**
     * Creates new form TapChiFrame
     */
    public TapChiFrame() throws SQLException {
        initComponents();
        DefaultTableModel defaultTableModel;
        TapChiService us = new TapChiService();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }

        };
        tapChiTableList.setModel(defaultTableModel);
        defaultTableModel.addColumn("idTaiLieu");
        defaultTableModel.addColumn("TenNXB");
        defaultTableModel.addColumn("SoBanPhatHanh");
        defaultTableModel.addColumn("TenTacGia");
        defaultTableModel.addColumn("SoTrang");
        setData(us.getAllTapChi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tapChiTableList = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 200));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("TẠP CHÍ");

        tapChiTableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tapChiTableList);

        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deleteBtn.setText("XÓA");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        refreshBtn.setText("REFRESH");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(backBtn)
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addComponent(deleteBtn)
                .addGap(47, 47, 47)
                .addComponent(refreshBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn)
                    .addComponent(deleteBtn)
                    .addComponent(refreshBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new mainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        TapChiService us = new TapChiService();
        int row = tapChiTableList.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(TapChiFrame.this, "Vui lòng chọn Tạp Chí muốn xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int comfirm = JOptionPane.showConfirmDialog(TapChiFrame.this, "Bạn có chắc chắn muốn xóa!");

            if (comfirm == JOptionPane.YES_OPTION) {
                int ID = Integer.valueOf(String.valueOf(tapChiTableList.getValueAt(row, 0)));

                try {
                    us.deleteTapChi(ID);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(TapChiFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                try {
                    setData(us.getAllTapChi());
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(TapChiFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        TapChiService us = new TapChiService();
        try {
            setData(us.getAllTapChi());
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(TapChiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void setData(List<TapChi> tapChis) throws SQLException {
        DefaultTableModel defaultTableModel;
        TapChiService us = new TapChiService();
        defaultTableModel = new DefaultTableModel();
        tapChiTableList.setModel(defaultTableModel);
        defaultTableModel.addColumn("id Tài Liệu");
        defaultTableModel.addColumn("Tên NXB");
        defaultTableModel.addColumn("Số Bản Phát Hành");
        defaultTableModel.addColumn("Số Phát Hành");
        defaultTableModel.addColumn("Tháng Phát Hành");
        for (TapChi tapchi : tapChis) {
            defaultTableModel.addRow(new Object[]{tapchi.getIdTaiLieu(), tapchi.getTenNXB(), tapchi.getSoBanPhatHanh(),
                tapchi.getSoPhatHanh(), tapchi.getThangPhatHanh()});
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable tapChiTableList;
    // End of variables declaration//GEN-END:variables
}
